name: 'Send Message Over Threema Broadcast API'
author: 'Fabio Tavernini - https://github.com/FabioTavernini'
description: 'Send a message to a Threema group using the Threema Broadcast API'
inputs:
  THREEMA_URL:
    description: 'url to your Threema broadcast Group (POST will be sent to this)'
    required: true
  THREEMA_XAPIKEY: 
    description: 'Your Threema X-API-Key'
    required: true
  message: 
    description: 'The message text to send to the group'
    required: true
  jobstatus: 
    description: 'Jobstatus - e.g $ {{ job.status }}'
    required: true
outputs:
  response:
    description: 'API response data'
  status:
    description: 'HTTP status code'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right-circle'
  color: 'green'