name: 'Send Message Over Threema Broadcast API'
description: 'Send a message to a Threema group using the Threema Broadcast API'
inputs:
  THREEMA_URL:
    description: 'url to your Threema broadcast Group (POST will be sent to this)'
    required: true
  THREEMA_XAPIKEY: 
    description: 'Your Threema X-API-Key'
    required: true
  message: 
    description: 'The message text to send to the group'
    required: true
outputs:
  time: 
    description: 'The time at which the message was sent'
runs:
  using: 'node20'
  main: 'dist/index.js'